name: CI & Publish

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: write

jobs:
  ci-publish:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20]

    steps:
      - uses: actions/checkout@v4

      - name: 安装 pnpm
        uses: pnpm/action-setup@v4
        with:
          version: "9.11.0"

      - name: 使用 Node.js ${{ matrix.node-version }} 版本
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Update npm
        run: npm install -g npm@latest

      - name: 安装依赖
        run: pnpm install

      - name: Typecheck
        run: pnpm run typecheck

      - name: Build
        run: pnpm run build

      - name: Test
        run: pnpm run test

      - name: 迭代版本号
        run: node ./.node/iteration-version.js -m ${{ vars.MAJOR_VN }} -n ${{ vars.MINOR_VN }}

      - name: 发布插件到 npm
        run: pnpm publish -r --access public --no-git-checks

      - name: 读取版本号
        id: read_version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT

      - name: 创建 GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.read_version.outputs.VERSION }}
          release_name: Release v${{ steps.read_version.outputs.VERSION }}
          draft: false
          prerelease: false
